name: 'Test-Deploy'

on:
  pull_request:
  push:
    branches: [main, feature/github-actions]

jobs:

  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: pre-commit/action@v3.0.1

  test-and-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # I prefer to use my Makefile to test the  commands instead of calling uv actions.
      - name: Install Python dependencies
        shell: bash
        run: |
          make install-dev

      - name: Run tests
        shell: bash
        run: |
          make test

      # build the python package. It is saved inside the dist folder
      - name: Build package
        shell: bash
        run: |
          make build-package

  deploy:
    #if: ${{ github.event.pull_request.merged == true }}
    # Add a dependency to the build job
    needs: [pre-commit,test-and-build]

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
